default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "profind" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "profind_password" } %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB") { "profind_development" } %>

test:
  <<: *default
  database: profind_test

production:
  primary: &primary_production
    <<: *default
    database: profind_production
  cache:
    <<: *primary_production
    database: profind_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: profind_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: profind_production_cable
    migrations_paths: db/cable_migrate
